family: EF1A
pfam:
  pf_re: '^PF00009([.][0-9]+)?$'
  ie_col: 9
  protein_col: 3

length:
  high_min: 420
  high_max: 480
  rescue_min: 400
  rescue_max: 520

blast:
  task: blastp
  evalue: 1e-10

# NP-safe top1 rules
rules:
  keep_top1_re: '(elongation factor 1-alpha|eEF1A)'
  remove_top1_re: '(EF-Tu|elongation factor Tu|TUFM)'
